### PR TITLE
Remove use of Nimbus Oauth2 SDK's CommonContentTypes

### PR DESCRIPTION
**Pull request by Avery-Dunn**
Removes the use of a file in Nimbus's oauth2-oidc-sdk, which was deprecated and causing issues in environments which used newer versions of that dependency. However, to avoid causing issues in environments which use older versions of this dependency (i.e., ones that don't have the new version of the deprecated file), this PR just removes the file's references and replaces it with our own implementation, rather than upgrade to the latest version.

Should solve the issue in https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/316, and can replace this PR https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/311.

### CODE REVIEW

**Review by sangonzal — APPROVED** [review]
:shipit:

**Comment by davidkarlsen** [comment]
Getting:
```
        ... 95 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.evry.fs.devtools.ad.AzureAdUserServiceImpl]: Factory method 'tietoAzureAdUserService' threw exception; nested exception is java.lang.NoSuchMethodError: 'net.minidev.json.JSONObject com.nimbusds.jwt.JWTClaimsSet.toJSONObject()'
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 109 common frames omitted
Caused by: java.lang.NoSuchMethodError: 'net.minidev.json.JSONObject com.nimbusds.jwt.JWTClaimsSet.toJSONObject()'
        at com.nimbusds.oauth2.sdk.auth.JWTAuthenticationClaimsSet.parse(JWTAuthenticationClaimsSet.java:166)
        at com.nimbusds.oauth2.sdk.auth.JWTAuthentication.<init>(JWTAuthentication.java:139)
        at com.nimbusds.oauth2.sdk.auth.PrivateKeyJWT.<init>(PrivateKeyJWT.java:251)
        at com.nimbusds.oauth2.sdk.auth.PrivateKeyJWT.parse(PrivateKeyJWT.java:286)
        at com.microsoft.aad.msal4j.ConfidentialClientApplication.createClientAuthFromClientAssertion(ConfidentialClientApplication.java:97)
        at com.microsoft.aad.msal4j.ConfidentialClientApplication.buildValidClientCertificateAuthority(ConfidentialClientApplication.java:89)
        at com.microsoft.aad.msal4j.ConfidentialClientApplication.initClientAuthentication(ConfidentialClientApplication.java:66)
        at com.microsoft.aad.msal4j.ConfidentialClientApplication.<init>(ConfidentialClientApplication.java:56)
        at com.microsoft.aad.msal4j.ConfidentialClientApplication.<init>(ConfidentialClientApplication.java:32)
        at com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.build(ConfidentialClientApplication.java:144)
        at com.evry.fs.devtools.ad.AzureAdUserServiceImpl.<init>(AzureAdUserServiceImpl.java:49)
```

with 1.8.1

**Comment by wavoe** [comment]
@Avery-Dunn 
This still seems to be an issue after the update to 1.9.0 using Spring Boot >= 2.4

```
Caused by: java.lang.NoSuchMethodError: com.nimbusds.jwt.JWTClaimsSet.toJSONObject()Lnet/minidev/json/JSONObject;
	at com.nimbusds.oauth2.sdk.auth.JWTAuthenticationClaimsSet.parse(JWTAuthenticationClaimsSet.java:166) ~[oauth2-oidc-sdk-8.23.1.jar:8.23.1]
	at com.nimbusds.oauth2.sdk.auth.JWTAuthentication.<init>(JWTAuthentication.java:139) ~[oauth2-oidc-sdk-8.23.1.jar:8.23.1]
	at com.nimbusds.oauth2.sdk.auth.PrivateKeyJWT.<init>(PrivateKeyJWT.java:251) ~[oauth2-oidc-sdk-8.23.1.jar:8.23.1]
	at com.nimbusds.oauth2.sdk.auth.PrivateKeyJWT.parse(PrivateKeyJWT.java:286) ~[oauth2-oidc-sdk-8.23.1.jar:8.23.1]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication.createClientAuthFromClientAssertion(ConfidentialClientApplication.java:97) ~[msal4j-1.9.0.jar:1.9.0]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication.buildValidClientCertificateAuthority(ConfidentialClientApplication.java:89) ~[msal4j-1.9.0.jar:1.9.0]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication.initClientAuthentication(ConfidentialClientApplication.java:66) ~[msal4j-1.9.0.jar:1.9.0]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication.<init>(ConfidentialClientApplication.java:56) ~[msal4j-1.9.0.jar:1.9.0]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication.<init>(ConfidentialClientApplication.java:32) ~[msal4j-1.9.0.jar:1.9.0]
	at com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.build(ConfidentialClientApplication.java:144) ~[msal4j-1.9.0.jar:1.9.0]
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.identifyToken(OAuthBearerLoginModule.java:316) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.login(OAuthBearerLoginModule.java:301) ~[kafka-clients-2.6.0.jar:na]
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:726) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663) ~[na:na]
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574) ~[na:na]
	at org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin.login(ExpiringCredentialRefreshingLogin.java:204) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerRefreshingLogin.login(OAuthBearerRefreshingLogin.java:150) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105) ~[kafka-clients-2.6.0.jar:na]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:158) ~[kafka-clients-2.6.0.jar:na]
	... 8 common frames omitted
```

**Comment by Avery-Dunn** [comment]
Hello @wavoe : The original issue was that the 8.23 version of `oauth2-oidc-sdk` removed a deprecated version of a file we used from the 7,4 version. Your issue seems to be that it can't find a method from `nimbus-jose-jwt` that a class in `oauth2-oidc-sdk` uses, which is weirder because both should be coming from Spring Boot.

I'm unable to recreate your error using Spring Boot 2.4, even after adding some extra stuff to specifically call that `.toJSONObject()` method. What version of `nimbus-jose-jwt` is your project using? 

I believe `nimbus-jose-jwt` is a transient dependency in our library and we just get it from `oauth2-oidc-sdk`, and before version 2.4 Spring Boot doesn't seem to have had it as a direct dependency either, so perhaps your project is still using a version from before these dependency updates?

**Comment by larzza** [comment]
Hi @Avery-Dunn!

Just like @wavoe I still have the issue after upgrading.

`./gradlew dependencies` reveals transitive dependencies  to `com.nimbusds:nimbus-jose-jwt` from `com.microsoft.azure:msal4j`.

Like so:

```
+--- com.microsoft.azure:msal4j:1.9.0
|    +--- com.nimbusds:oauth2-oidc-sdk:8.23.1
|    |    +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
|    |    +--- com.nimbusds:content-type:2.1
|    |    +--- net.minidev:json-smart:[1.3.1,2.3] -> 2.3
|    |    |    \--- net.minidev:accessors-smart:1.2
|    |    |         \--- org.ow2.asm:asm:5.0.4
|    |    +--- com.nimbusds:lang-tag:1.4.4
|    |    \--- com.nimbusds:nimbus-jose-jwt:8.18 -> 9.1.3
|    |         \--- com.github.stephenc.jcip:jcip-annotations:1.0-1
```

 `com.microsoft.azure:msal4j:1.9.0` -> `com.nimbusds:oauth2-oidc-sdk:8.23.1` ->  `com.nimbusds:nimbus-jose-jwt:8.18`

But we get `com.nimbusds:nimbus-jose-jwt:9.13`, I assume because of upgraded dependencies in Springboot 2.4 

- In `com.nimbusds:nimbus-jose-jwt:8.18`: `public static JWTClaimsSet parse(final JSONObject json)`
- In  `com.nimbusds:nimbus-jose-jwt:9.13`:  `public static JWTClaimsSet parse(final Map<String, Object> json)`

Conclusion: `msal4j` need a newer dependency to `com.nimbusds:oauth2-oidc-sdk` than `8.23.1`.

Does that make sense?
