### ISSUE TITLE
[Bug] NoSuchMethodError: 'com.microsoft.aad.msal4j.AbstractClientApplicationBase$Builder com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.proxy(java.net.Proxy)'

### ISSUE THREAD

**Issue by jerlac** [AzureAD/microsoft-authentication-library-for-java#850]
### Library version used

1.16.2

### Java version

17

### Scenario

ConfidentialClient - web site (AcquireTokenByAuthCode)

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

when using proxy to establish a connection, since msal4j 1.16.x, i encounter the error.

### Relevant code snippets

```csharp
occurs in .proxy(...):

InetSocketAddress socketAddress= new InetSocketAddress(...);
Proxy proxy = new Proxy(Proxy.Type.HTTP, socketAddress);
InputStream p12Stream = new ByteArrayInputStream(...)
String certPwd ="...";

ConfidentialClientApplication.builder("clientId", 
    ClientCredentialFactory.createFromCertificate(p12Stream, certPwd)
.authority(...)
.proxy(proxy)
.build();
```

### Expected behavior

code works well with previous version 1.15.1 and lower

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

1.15.1

**Comment by bgavrilMS** [comment]
@Avery-Dunn - what more information can @jerlac provide? Did we remove the "proxy" method? 

@jerlac - we generally want app developers who use proxy to customize their entir Http Client instead. We tried to support proxies and it's just a bug farm.

**Comment by Avery-Dunn** [comment]
Hello @jerlac : I'm having trouble reproducing your error, so to clarify a few things:
- Are you using the msal4j package directly, and are any other dependencies using it?
- You chose the "This is a new app or experiment" option, but said the code was working in a previous version. So did you have a working app, and after only upgrading msal4j this started happening?
- 1.5.0 and 1.15.1 introduced some API issues that were fixed in 1.16.0. Have you used any of the 1.14.x versions, and if so did you see this issue?

This seems very similar to an issue we had a few months ago and was fixed in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/828. However, that version only re-introduced the APIs to their original base classes, it did not remove any API and they haven't been changed since.

**Comment by jerlac** [comment]
Hello,
i use msal4j directly with this dependency groupid= com.microsoft.azure, artifactid= msal4j .
My app is in Dev and Staging environment.
The app works between msal4j version 1.14.3 and 1.15.1, but since 1.16.x,  it fails.

I tried to custom the httpClient as recommended by using this sample:
https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Configure-Http-Client#msal-lets-you-provide-your-own-http-client-for-supporting-fine-grained-configurations

i give the proxy setting, and when i run the app, i have the same error :
java.lang.NoSuchMethodError: 'com.microsoft.aad.msal4j.AbstractClientApplicationBase$Builder com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.httpClient(com.microsoft.aad.msal4j.IHttpClient)'

 private static void getOrBuildApp(MsAuthenticationClientProperties msAuthenticationClientProperties, SpoServiceClientProperties spoServiceClientProperties) {

    if (app == null) {
        try {
           InputStream p12Stream = new ByteArrayInputStream(Files.readAllBytes(Paths.get(msAuthenticationClientProperties.getCertPath())));
            String certPwd = msAuthenticationClientProperties.getCertPassword();

            MsAuthHttpClientAdapter msAuthHttpClientAdapter = new MsAuthHttpClientAdapter(spoServiceClientProperties);

            app = ConfidentialClientApplication.builder(
                            msAuthenticationClientProperties.getClientId(),
                            ClientCredentialFactory.createFromCertificate(p12Stream, certPwd))
                    .authority(getAuthorityBaseUrl(msAuthenticationClientProperties) + msAuthenticationClientProperties.getTenantId() + "/")
                    .httpClient(msAuthHttpClientAdapter)
                    .build();
        } catch (Exception e) {
            throw new TechnicalException(e);
        }
    }
}

...
public class MsAuthHttpClientAdapter implements IHttpClient {
    private final OkHttpClient okHttpClient;

    public MsAuthHttpClientAdapter(SpoServiceClientProperties spoServiceClientProperties) {
        final InetSocketAddress socketAddress = new InetSocketAddress(spoServiceClientProperties.getProxy().getHostName(),
                spoServiceClientProperties.getProxy().getPort());

        // Setup proxy for the Graph client
        final Proxy proxy = new Proxy(Proxy.Type.HTTP, socketAddress);
        okHttpClient = new OkHttpClient.Builder().proxy(proxy).build();
    }

 ...

**Comment by jerlac** [comment]
Hello,
as i saw a similar error with Builder.httpclient, i was inside the code with my IDE and i saw that the first class, AbstractClientApplicationBase, came from jar v1.16.2, but the super in AbstractApplicationBase cames from jar v1.15.1 .

As my project references only msal4j v1.16.2, there was a mistake.
With my IDE, intellij IDEA, i checked External Libraries in the Project view and i saw too the 2 msal4j jar version.

So i went to my maven repository, i deleted the v1.15.1 folder and i ran the project, this time i got :
java.lang.NoClassDefFoundError: com/microsoft/aad/msal4j/IClientCredential

so there is a bad reference to old msal4j version somewhere.
I did mvn clean, rebuilt the project and this time i didn't see the previous version in the External Libraries view.

I launched the project and this time it worked with the usage of .proxy or .httpClient in the ConfidenialClientApplication.builder().

We can close this issue.

**Comment by Avery-Dunn** [comment]
@jerlac : Thanks for the investigation! 1.15.x had API issues that caused these sorts of errors when different dependencies used different msal4j versions, so it makes sense that different cached versions could cause the error too.

Closing this issue, if you run into any other issues feel free to re-open this thread or start a new one.
